### PR TITLE
Set lm util to None

### PR DESCRIPTION
**Pull request by Atticus1806**
Fixes error that lm util is not in compiled rasr anymore

### CODE REVIEW

**Comment by JackTemaki** [comment]
I think this can be removed completely, not only be set to None.

**Review by christophmluscher — CHANGES_REQUESTED** [review]
There are Jobs which depend on `lm_util_exe`:
```
CreateLmImageJob
ComputePerplexityJob
```
@curufinwe @michelwi is this relevant for AppTek?

**Comment by michelwi** [comment]
why is it not in compiled rasr any more?

**Comment by christophmluscher** [comment]
> why is it not in compiled rasr any more?

the flag `TOOLS += Lm` got removed. Not 100% sure if the code for the tool also got removed..

**Review by michelwi — CHANGES_REQUESTED** [review]
> @michelwi is this relevant for AppTek?

yes. And also the failed pipeline is a genuine breaking of hashes of one of our setups. Therefore request changes.

Actually, we should abandon this PR and try to fix that LM_util is not compiled any more.

**Comment by christophmluscher** [comment]
`TOOLS += Lm` probably adding this to `Modules.Make` should fix this..

**Comment by michelwi** [comment]
>  the failed pipeline is a genuine breaking of hashes of one of our setups.

I think the problem is that in FilterSegmentsByAlignmentConfidenceJob https://github.com/rwth-i6/i6_core/blob/e3ea366746eab8c7639ff680d40ce49a6870b6c5/corpus/filter.py#L73 The full crp are hashed. If one member is removed this changes the hash.

The version of this PR where it was set to `None` would, I think, still work for us (the hashes were correct at least).
And we use a different compile job for the AppTek RASR.

**Review by michelwi — APPROVED** [review]
I am ok with setting to None here. We do set this elsewhere.

**Comment by Atticus1806** [comment]
@christophmluscher is this fine? Then I would merge

**Review by christophmluscher — APPROVED** [review]

**Pull request merged**
