### PR TITLE
Willi add multi channel strategy

### PR DESCRIPTION
**Pull request by michelwi**
Same as https://github.com/rwth-i6/i6_core/pull/352 but with fixed `__sis_hash_exclude__`

### CODE REVIEW

**Comment by vieting** [comment]
Since #352 was merged, shouldn't this branch be rebased?

**Comment by christophmluscher** [comment]
I think #352 got reverted by #358

**Comment by michelwi** [comment]
yes.. As I only noticed belatedly in https://github.com/rwth-i6/i6_core/pull/352#discussion_r1107135915 the current form breaks hashes of existing setups. So we immediately reverted it.

And this is me reproposing the changes with correct hashes (this time I tested it beforehand)

**Review by JackTemaki — APPROVED** [review]

**Review by vieting — COMMENTED** [review]
If the hash issues are now resolved, I think we can merge.

**Review by vieting — APPROVED** [review]

**Review by christophmluscher — APPROVED** [review]

**Pull request merged**
