### PR TITLE
Filter job keep synt tok - Bug fix.

### PR DESCRIPTION
**Pull request by sarahberanek**
Apparently, nobody used the option after implementing :nerd_face:  

if there is no synt tok in a lemma, then - when setting the `check_synt_tok` option - it will always be true, because
`all(empty list) = True`. This fixes it.

### CODE REVIEW

**Comment by Atticus1806** [comment]
If I understood correctly the AppTek test fails because the PR is from a private branch and not from a repo branch right?

**Comment by sarahberanek** [comment]
> If I understood correctly the AppTek test fails because the PR is from a private branch and not from a repo branch right?

Is this new? This didn't happen last time. @michelwi will know 😎

**Review by michelwi — APPROVED** [review]
> If I understood correctly the AppTek test fails because the PR is from a private branch and not from a repo branch right?

That is correct. Doing PRs from a branch rather than a fork is the preferred method.

**Comment by michelwi** [comment]
> I didnt have permission back in the day, thats why I used this way and now sticked with it. Do you want me to re-open the PR from a branch from i6-core?

I don't think it is necessary to redo this PR.
But please check if you are allowed to create branches now and then use this for future PRs, thanks.

**Comment by JackTemaki** [comment]
> > I didnt have permission back in the day, thats why I used this way and now sticked with it. Do you want me to re-open the PR from a branch from i6-core?
> 
> I don't think it is necessary to redo this PR. But please check if you are allowed to create branches now and then use this for future PRs, thanks.

@sarahberanek I added access for you!

**Review by JackTemaki — APPROVED** [review]

**Comment by sarahberanek** [comment]
> > I didnt have permission back in the day, thats why I used this way and now sticked with it. Do you want me to re-open the PR from a branch from i6-core?
> 
> I don't think it is necessary to redo this PR. But please check if you are allowed to create branches now and then use this for future PRs, thanks.

So can we even merge now with this check failed?
Thanks, Nick for the access!

**Pull request merged**
