### PR TITLE
Fix for the decision tree logic in the BlissToOggZipJob

### PR DESCRIPTION
**Pull request by Max-Ryujin**
This PR is a fix for #485

### CODE REVIEW

**Review by JackTemaki — APPROVED** [review]

**Review by vieting — APPROVED** [review]

**Comment by JackTemaki** [comment]
@michelwi do you know what happened for the test?

**Comment by michelwi** [comment]
> @michelwi do you know what happened for the test?

pr on a fork instead of a branch. `Max-Ryujin/i6_core` does not have permission to trigger our pipeline.

But as this change is in a `run` function, it cannot affect our pipeline. Therefore green light from our side.

**Comment by JackTemaki** [comment]
Oh did not see that, all right!

**Comment by vieting** [comment]
Then we can merge, right? @michelwi @JackTemaki

**Pull request merged**
