### PR TITLE
Replaced rasr.PathWithPrefixFlowAttribute with the plain path

### LINKED ISSUE #67: EstimateLDAMatrixJob wrong usage of rasr.PathWithPrefixFlowAttribute?
This is the error that led me to find the problem in #66.
In https://github.com/rwth-i6/i6_core/blob/88a4f225a9e4609a76d5e33c247d5ced103d9079/lda/estimate.py#L341 `between_class_scatter_matrix_file` and `within_class_scatter_matrix_file` are assigned as 
```
 config.acoustic_model_trainer.lda_estimator.between_class_scatter_matrix_file = rasr.PathWithPrefixFlowAttribute(
            "xml:", between_class_scatter_matrix
        )
        config.acoustic_model_trainer.lda_estimator.within_class_scatter_matrix_file = (
            rasr.PathWithPrefixFlowAttribute("xml:", within_class_scatter_matrix)
        )
```
which are then printed in the config as python objects and not strings. Also, these files are not xml.

### PR DESCRIPTION
**Pull request by mattiadg**
fixes #67

### CODE REVIEW

**Review by michelwi — CHANGES_REQUESTED** [review]
I think you still need to specify the file format with the prefix `xml:`

**Comment by curufinwe** [comment]
Not needed anymore due to #69

**Comment by mattiadg** [comment]
Not really, the code as it is still print the object in the config instead of the path
```
[acoustic-model-trainer.lda-estimator]
between-class-scatter-matrix-file = <i6_core.rasr.flow.PathWithPrefixFlowAttribute object at 0x7efe568d63c8>
output-precision                  = 20
projector-matrix-file             = xml:lda.matrix
reduced-dimesion                  = 40
results.channel                   = output-channel
within-class-scatter-matrix-file  = <i6_core.rasr.flow.PathWithPrefixFlowAttribute object at 0x7efe568d6470>
```
At the very least, we should call `get`, which is not done now.
Also, are you sure that we should use a FlowAttribute in the config?

**Comment by JackTemaki** [comment]
@curufinwe there are two cases for this scenario:
- the xml prefix is not needed, and we can add a "path" directly 
- the xml prefix is needed, then we can use the already built-in `DelayedAdd` or `DelayedFormat` of Sisyphus, instead of introducing a new class like `PathWithPrefixFlowAttribute`.

**Comment by curufinwe** [comment]
I see. Then let's just use the DelayedFormat object and completely remove PathWithPrefixFlowAttribute

**Review by michelwi — APPROVED** [review]

**Review by curufinwe — APPROVED** [review]

**Pull request merged**
