### PR TITLE
Fix bug in LexiconWriteFromFile job to allow multiple pronunciation variants

### PR DESCRIPTION
**Pull request by mmz33**
This PR fixes the bug in writing lexicon from file by allowing multiple pronunciation variants.

### CODE REVIEW

**Comment by mmz33** [comment]
btw, i was thinking also if we should use a dict to check for already seen lemma instead of `last_lemma`. Because this requires that the orth need to be sorted in the file or at least this need to be done.

**Review by curufinwe — APPROVED** [review]
I think the only bug here is in `if p not in lemma.phon:` where we should look at `p not in last_lemma.phon`. Everything else could remain the same. But this code also works. So OK from my side.

**Comment by curufinwe** [comment]
@JackTemaki  what do you think? (IIRC you wrote the original version)

**Comment by mmz33** [comment]
> I think the only bug here is in `if p not in lemma.phon:` where we should look at `p not in last_lemma.phon`. Everything else could remain the same. But this code also works. So OK from my side.

yes but also no need to create the `lemma` object outside the else branch

**Review by JackTemaki — APPROVED** [review]
Yeah, this was a really bad mistake from my side, the new version is definitely correct, I just tested it again. It seems I did not check properly after fixing the repeated entry issue...

**Comment by mmz33** [comment]
@curufinwe can this be merged?

**Review by JackTemaki — APPROVED** [review]

**Pull request merged**
