### PR TITLE
Refactor segment jobs

### PR DESCRIPTION
**Pull request by JackTemaki**
It seems a complete file was missed during refactoring, and I think we should fix this now (or never).

I think it would be best that all people that already build setups with this confirm this PR, so that I can see that everyone is aware of the API (not hash) changes.

### CODE REVIEW

**Review by michelwi — APPROVED** [review]
I wasn't using it yet and would be fine with the change

**Review by mmz33 — APPROVED** [review]

**Review by vieting — CHANGES_REQUESTED** [review]
There is a usage of the `ShuffleAndSplitSegmentsJob` in `linear_adaptation_layer.py` which should be updated. Also, I guess we need an associate PR for i6_experiments?

**Review by curufinwe — DISMISSED** [review]

**Comment by mattiadg** [comment]
> It seems a complete file was missed during refactoring, and I think we should fix this now (or never).
> 
> I think it would be best that all people that already build setups with this confirm this PR, so that I can see that everyone is aware of the API (not hash) changes.

by refactoring here, you mean updating to the new conventions?

**Comment by JackTemaki** [comment]
> > It seems a complete file was missed during refactoring, and I think we should fix this now (or never).
> > I think it would be best that all people that already build setups with this confirm this PR, so that I can see that everyone is aware of the API (not hash) changes.
> 
> by refactoring here, you mean updating to the new conventions?

Yes exactly

**Comment by JackTemaki** [comment]
> There is a usage of the `ShuffleAndSplitSegmentsJob` in `linear_adaptation_layer.py` which should be updated. Also, I guess we need an associate PR for i6_experiments?

Done, and yes I will try to do a PR that also fixes this for `i6_experiments/common`

**Review by curufinwe — APPROVED** [review]

**Review by mattiadg — APPROVED** [review]

**Review by vieting — APPROVED** [review]

**Review by Marvin84 — APPROVED** [review]

**Review by michelwi — APPROVED** [review]

**Review by christophmluscher — APPROVED** [review]

**Review by papar22 — APPROVED** [review]

**Review by mmz33 — APPROVED** [review]

**Pull request merged**
